version: '3'
services:
  web:
    build: .
    ports:
      - "5050:80"
    volumes:
      - .:/usr/src/app
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
    command: flask run --port=80 --host=0.0.0.0